name             "apps"
maintainer       "Daniel O'Connor"
maintainer_email "daniel.oconnor@gmail.com"
license          "BSD"
description      "Installs/Configures apps"
long_description ""
version          "0.0.1"
depends          "rbenv"
depends          "ruby_2"
depends          "nginx"
depends          "logrotate"
depends          "ssh"
depends          "postgresql"
depends          "sysctl"
